from pathlib import Path

def plan(result):
    items=[]
    for host in result["desired"]:
        identity=host.identity; manual=[p for p in result["access_paths"] if p.get("identity")==identity and p.get("kind")=="ssh"]
        observed=next((r for r in result["rows"] if r.get("identity")==identity and r.get("name")),None)
        if not manual:
            bindings=host.attrs.get("bindings",{}).get("ssh",{}); aliases=bindings.get("aliases",[])
            if observed and aliases and bindings.get("user"):
                inherited=next((p for p in result["access_paths"] if p.get("kind")=="ssh" and p.get("user")==bindings["user"] and p.get("effective_config",{}).get("effective",{}).get("identityfile")),None)
                effective=inherited.get("effective_config",{}).get("effective",{}) if inherited else {}
                entry={"alias":aliases[0],"hostname":observed["name"],"user":bindings["user"],"port":bindings.get("port",22)}
                if effective.get("identityfile"): entry["identityfile"]=effective["identityfile"]
                if effective.get("identitiesonly"): entry["identitiesonly"]=effective["identitiesonly"]
                items.append({"identity":identity,"manual":"unknown","proposal":"generate","action":"create-preview-entry","reason":"explicit SSH binding plus observed Tailscale name and existing key metadata","entry":entry})
            else:
                items.append({"identity":identity,"manual":"unknown","proposal":"none","action":"none","reason":"no observed SSH alias or explicit SSH user"})
            continue
        path=manual[0]; effective=path.get("effective_config",{}).get("effective",{})
        if path.get("classification")=="local-forwarded-or-child": reason="working special manual path; do not replace with Tailscale endpoint"
        elif effective and observed and observed.get("addresses") and effective.get("hostname") in observed["addresses"]: reason="existing effective path is equivalent to observed Tailscale address"
        else: reason="existing manual path retained; no justified behavior change"
        items.append({"identity":identity,"manual":{"alias":path["name"],"hostname":effective.get("hostname"),"port":effective.get("port"),"user":effective.get("user"),"classification":path["classification"]},"proposal":"preserve-manual","action":"none","reason":reason})
    return items

def render(plan_items):
    lines=["# GENERATED BY NETBOT", "# PREVIEW ONLY — NOT INSTALLED", "# This artifact does not modify or replace existing SSH configuration.", ""]
    for item in plan_items:
        lines.append(f"# {item['identity']}: {item['proposal']} ({item['reason']})")
        if item.get("entry"):
            e=item["entry"]; lines += [f"Host {e['alias']}",f"    HostName {e['hostname']}",f"    User {e['user']}",f"    Port {e['port']}"]
            if e.get("identityfile"):
                lines += [f"    IdentityFile {e['identityfile'][0]}"]
            if e.get("identitiesonly"): lines += [f"    IdentitiesOnly {e['identitiesonly']}"]
            lines += [""]
    lines.append("")
    return "\n".join(lines)

def render_installed(plan_items):
    lines=["# GENERATED BY NETBOT", "# DO NOT EDIT MANUALLY", "# Source: repository generated/50-netbot.conf", "# Installed by explicit netbot ssh-apply", ""]
    for item in plan_items:
        lines.append(f"# {item['identity']}: {item['proposal']} ({item['reason']})")
        if item.get("entry"):
            e=item["entry"]; lines += [f"Host {e['alias']}",f"    HostName {e['hostname']}",f"    User {e['user']}",f"    Port {e['port']}"]
            if e.get("identityfile"):
                lines += [f"    IdentityFile {e['identityfile'][0]}"]
            if e.get("identitiesonly"): lines += [f"    IdentitiesOnly {e['identitiesonly']}"]
            lines += [""]
    lines.append("")
    return "\n".join(lines)

def write_preview(plan_items, path: Path):
    path.parent.mkdir(parents=True,exist_ok=True); path.write_text(render(plan_items)); return path
