version: 1
authority: arasaka

peer_policy:
  default: topology

agents:
  temporary:
    desired_version: "0.3.0"

hosts:

  arasaka:
    class: core
    kind: physical
    observed_names:
      - arasaka
    bindings:
      tailscale:
        node_id: "4582162682695456"
        name: arasaka
      ssh:
        aliases:
          - arasaka
        user: zero
        connections:
          orion:
            identity_file: ~/.ssh/id_ed25519_arasaka
          netbot-test:
            identity_file: ~/.ssh/id_ed25519_arasaka
  kiroshi:
    class: core
    kind: physical
    bindings:
      tailscale:
        node_id: "961106256404732"
        name: kiroshi
      ssh:
        aliases:
          - kiroshi
        user: rafael
  mikoshi:
    class: core
    bindings:
      tailscale:
        node_id: "813577720113717"
        name: mikoshi
      ssh:
        aliases:
          - mikoshi
        user: zero
  orion:
    class: satellite
    kind: physical
    os_family: linux
    bindings:
      tailscale:
        node_id: "3614159598068992"
        name: orion
      ssh:
        aliases:
          - orion
        user: lourdes
        port: 22
  orthanc-postgres:
    class: child
    kind: vm
    parent: arasaka
    observed_names:
      - OrthancPostgres-Mac
  lourdes:
    class: unknown
    observed_names:
      - lourdes
    lifecycle: retired
    superseded_by: orion
  oracle:
    class: unknown
    observed_names:
      - oracle
    bindings:
      tailscale:
        node_id: "4789064075134476"
        name: oracle
      ssh:
        aliases:
          - oracle
        user: rafael
  netbot-test:
    class: unknown
    bindings:
      tailscale:
        node_id: "1962171247067809"
        name: orthanc-db
      ssh:
        aliases:
          - netbot-test
        user: zero
